use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ErrorCode {
    AlreadyInitialized = 1,
    NotAuthorized = 2,
    MarketNotFound = 3,
    MarketClosed = 4,
    MarketStillActive = 5,
    InvalidOutcome = 6,
    InvalidBetAmount = 7,
    InsufficientBalance = 8,
    OracleFailure = 9,
    CircuitBreakerOpen = 10,
    DisputeWindowClosed = 11,
    VotingNotStarted = 12,
    VotingEnded = 13,
    AlreadyVoted = 14,
    FeeTooHigh = 15,
    MarketNotActive = 16,
    DeadlinePassed = 17,
    CannotChangeOutcome = 18,
    MarketNotDisputed = 19,
    MarketNotPendingResolution = 20,
    AdminNotSet = 21,
    ContractPaused = 22,
    GuardianNotSet = 23,
    TooManyOutcomes = 24,
    TooManyWinners = 25,
    PayoutModeNotSupported = 26,
    InsufficientDeposit = 27,
    TimelockActive = 28,
    UpgradeNotInitiated = 29,
    InsufficientVotes = 30,
    AlreadyVotedOnUpgrade = 31,
    InvalidWasmHash = 32,
    UpgradeFailed = 33,
    ParentMarketNotResolved = 34,
    ParentMarketInvalidOutcome = 35,
    InsufficientVotingWeight = 36,
    MarketNotCancelled = 37,
    BetNotFound = 38,
    ResolutionNotReady = 39,
    DisputeWindowStillOpen = 40,
    NoMajorityReached = 41,
    AssetClawedBack = 42,
    GovernanceTokenNotSet = 43,
    StalePrice = 44,
    ConfidenceTooLow = 45,
    NoWinnings = 46,
    MarketNotResolved = 47,
    AlreadyClaimed = 48,
    InvalidReferrer = 49,
    InvalidAmount = 50,
}
